name: Check & send alert

on:
  schedule:
    - cron: '0 */1 * * *' # hourly
  workflow_dispatch:

env:
  severity: Severe
  region: Zagreb
  language: hr

jobs:
  parse-and-send-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Download XML
        run: |
          curl https://meteo.hr/upozorenja/cap_hr_today.xml > alerts.xml
          cat alerts.xml
      - name: Parse XML
        id: parse
        run: |
          yq -oy '.alert.info[] | select(.language == "${{ env.language }}" and .severity == "${{ env.severity }}" and (.area.areaDesc | contains("${{ env.region }}"))) | "<p><h1>\(.event)</h1><p><b>\(.onset)</b></p><p>\(.description)</p><p>\(.instruction)</p></p>"' alerts.xml > output.html
          size=$(stat -c%s output.html)
          echo "File size: $size"
          echo "size=$size" >> $GITHUB_OUTPUT
          echo "<p><a href='https://meteo.hr/naslovnica-upozorenja.php?tab=upozorenja'>Vidi detalje</a></p>" >> output.html
          cat output.html
      - name: Send mail
        if: steps.parse.outputs.size > 45
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp+starttls://${{secrets.GMAIL_ADDRESS}}:${{secrets.GMAIL_APP_PASSWORD}}@smtp.gmail.com:465
          subject: DHMZ upozorenje
          to: ${{secrets.GMAIL_ADDRESS}}
          from: Marko Bjelac
          html_body: file://output.html
